global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s

  # 如果需要监控消费者积压，可以添加自定义exporter
  # - job_name: 'kafka-consumer-lag'
  #   static_configs:
  #     - targets: ['host.docker.internal:9309']
  #   scrape_interval: 30s
